name: 'Mdw setup'
description: 'Setup elixir and get Mdw deps'

runs:
  using: "composite"
  steps:
    - uses: erlef/setup-beam@v1
      with:
        otp-version: 26.2.4
        elixir-version: 1.16.2
        version-type: strict

    - name: Get Mdw dependencies
      shell: bash
      run: mix deps.get
