name: 'Mdw setup'
description: 'Setup elixir and get Mdw deps'

runs:
  using: "composite"
  steps:
    - uses: erlef/setup-beam@v1
      with:
        otp-version: 23.3.4.17
        elixir-version: 1.13.4

    - name: Get Mdw dependencies
      shell: bash
      run: mix deps.get