name: 'Common Test setup'
description: 'Setup docker compose'

runs:
  using: "composite"
  steps:
    - name: Upgrade docker-compose
      shell: bash
      run: |
        sudo rm /usr/local/bin/docker-compose
        curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > docker-compose
        chmod +x docker-compose
        sudo mv docker-compose /usr/local/bin/docker-compose
