name: 'Node setup'
description: 'Setup Aeternity Node'

runs:
  using: "composite"
  steps:
    - name: Setup Node
      shell: bash
      run: |
        curl -L https://github.com/aeternity/aeternity/releases/download/v7.0.0-rc1/aeternity-v7.0.0-rc1-ubuntu-x86_64.tar.gz -o aeternity.tgz\
        && mkdir -p ${NODEROOT}/rel/aeternity && tar xf aeternity.tgz -C ${NODEROOT}/rel/aeternity && cp -rf ${NODEROOT}/rel/aeternity/lib/ ${NODEROOT}
