name: Dockerhub Dev Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "master"

env:
  APP: "ae_mdw"

jobs:
  dockerhub:
    name: "Publish dev branches to Dockehub"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # Only worked for us with this option on
        with:
          install: true

      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Extract metadata for docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: aeternity/${{ env.APP }}
          tags: |
            type=edge
            type=ref,event=pr
            type=sha,prefix=

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
